version: "3"

vars:
  ENV_NAME: { sh: "pwd | xargs basename" }
  CC: { sh: "yq '.env.cc' packages.toml" }
  CXX: { sh: "yq '.env.cxx' packages.toml" }
  MPI_URL: { sh: "yq '.env.mpi.url' packages.toml" }
  MPI_TGZ: { sh: "yq '.env.mpi.url' packages.toml | xargs basename" }
  MPI_SRC_DIR: { sh: "basename {{ .MPI_TGZ }} .tar.gz" }

tasks:
  default:
    cmds:
      - task: building_mpi

  module:
    cmds:
      - gomplate -d packages.toml -f ./module.lua -o ../modulefiles/{{ .ENV_NAME }}.lua

  fetching_mpi:
    cmds:
      - wget {{ .MPI_URL }}
      - tar xzvf {{ .MPI_TGZ }}
      - defer: rm -fr {{ .MPI_TGZ }}

  building_mpi:
    deps: [fetching_mpi]
    dir: "{{ .MPI_SRC_DIR }}"
    cmds:
      - ./configure --prefix=$HOME/.hpc/{{ .ENV_NAME }} CC={{ .CC }} CXX={{ .CXX }} --enable-mpi-fortran=no
      - make -j
      - make -j install
